import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'

// =============================================================================
// Plantilla PDF — IRS Form 1099-NEC (Nonemployee Compensation)
// =============================================================================
// Solo se genera para contractors (employee_type = 'contractor') que
// recibieron $600 o más en el año.
// =============================================================================

export type Form1099NECData = {
  taxYear: number
  payer: {
    name: string
    tin?: string
    addressLine1?: string
    city?: string
    region?: string
    postalCode?: string
  }
  recipient: {
    fullName: string
    tinLastFour?: string | null
    addressLine1?: string
    city?: string
    region?: string
    postalCode?: string
  }
  box1NonemployeeCompensationCents: number
  box4FederalTaxWithheldCents: number
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica' },
  header: { fontSize: 14, fontWeight: 'bold', marginBottom: 4 },
  subheader: { fontSize: 10, color: '#666', marginBottom: 12 },
  section: { marginBottom: 14, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: '#ddd', borderBottomStyle: 'solid' },
  row: { flexDirection: 'row', marginBottom: 4 },
  label: { width: 200, color: '#666' },
  value: { fontWeight: 'bold' },
  boxesGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 },
  box: { width: '50%', padding: 6 },
  boxLabel: { fontSize: 8, color: '#666', marginBottom: 2 },
  boxValue: { fontSize: 12, fontWeight: 'bold' },
})

function fmt(cents: number): string {
  return `$${(cents / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

export function Form1099NECPdf({ data }: { data: Form1099NECData }) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.header}>Form 1099-NEC — Nonemployee Compensation</Text>
        <Text style={styles.subheader}>Tax year {data.taxYear} · Generated by MyJova</Text>

        <View style={styles.section}>
          <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>Payer (employer)</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Name:</Text>
            <Text style={styles.value}>{data.payer.name}</Text>
          </View>
          {data.payer.tin && (
            <View style={styles.row}>
              <Text style={styles.label}>TIN:</Text>
              <Text style={styles.value}>{data.payer.tin}</Text>
            </View>
          )}
        </View>

        <View style={styles.section}>
          <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>Recipient (contractor)</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Name:</Text>
            <Text style={styles.value}>{data.recipient.fullName}</Text>
          </View>
          {data.recipient.tinLastFour && (
            <View style={styles.row}>
              <Text style={styles.label}>TIN (last 4):</Text>
              <Text style={styles.value}>•••-••-{data.recipient.tinLastFour}</Text>
            </View>
          )}
        </View>

        <View style={styles.boxesGrid}>
          <View style={styles.box}>
            <Text style={styles.boxLabel}>Box 1 — Nonemployee compensation</Text>
            <Text style={styles.boxValue}>{fmt(data.box1NonemployeeCompensationCents)}</Text>
          </View>
          <View style={styles.box}>
            <Text style={styles.boxLabel}>Box 4 — Federal income tax withheld</Text>
            <Text style={styles.boxValue}>{fmt(data.box4FederalTaxWithheldCents)}</Text>
          </View>
        </View>
      </Page>
    </Document>
  )
}
