import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from '@react-pdf/renderer'

// =============================================================================
// Plantilla PDF — IRS Form W-2 (Wage and Tax Statement)
// =============================================================================
// Layout simplificado: NO es el formulario oficial pixel-perfect, sino una
// versión legible que cumple con incluir todos los boxes obligatorios.
// Para producción + e-filing, se debería integrar con un servicio de
// formularios oficiales (Track1099, Greenshades, etc.) que genere el PDF
// con el layout escaneable de IRS.
// =============================================================================

export type W2Data = {
  taxYear: number
  employee: {
    fullName: string
    addressLine1?: string
    addressLine2?: string
    city?: string
    region?: string
    postalCode?: string
    taxIdLastFour?: string | null
  }
  employer: {
    name: string
    ein?: string
    addressLine1?: string
    city?: string
    region?: string
    postalCode?: string
  }
  // Box totals (en centavos en código; mostramos en dólares en el PDF)
  box1WagesCents: number
  box2FederalTaxCents: number
  box3SocialSecurityWagesCents: number
  box4SocialSecurityTaxCents: number
  box5MedicareWagesCents: number
  box6MedicareTaxCents: number
  box16StateWagesCents: number
  box17StateTaxCents: number
  box15StateCode?: string
  // Local (municipal) — solo se imprimen si hay localidad con retención.
  box18LocalWagesCents?: number
  box19LocalTaxCents?: number
  box20LocalityName?: string
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica' },
  header: { fontSize: 14, fontWeight: 'bold', marginBottom: 4 },
  subheader: { fontSize: 10, color: '#666', marginBottom: 12 },
  section: { marginBottom: 14, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: '#ddd', borderBottomStyle: 'solid' },
  row: { flexDirection: 'row', marginBottom: 4 },
  label: { width: 200, color: '#666' },
  value: { fontWeight: 'bold' },
  boxesGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 },
  box: { width: '50%', padding: 6 },
  boxLabel: { fontSize: 8, color: '#666', marginBottom: 2 },
  boxValue: { fontSize: 12, fontWeight: 'bold' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#999', textAlign: 'center' },
})

function fmt(cents: number): string {
  return `$${(cents / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

export function W2Pdf({ data }: { data: W2Data }) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.header}>Form W-2 — Wage and Tax Statement</Text>
        <Text style={styles.subheader}>Tax year {data.taxYear} · Generated by MyJova</Text>

        <View style={styles.section}>
          <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>Employee</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Name:</Text>
            <Text style={styles.value}>{data.employee.fullName}</Text>
          </View>
          {data.employee.taxIdLastFour && (
            <View style={styles.row}>
              <Text style={styles.label}>SSN (last 4):</Text>
              <Text style={styles.value}>•••-••-{data.employee.taxIdLastFour}</Text>
            </View>
          )}
          {data.employee.addressLine1 && (
            <View style={styles.row}>
              <Text style={styles.label}>Address:</Text>
              <Text style={styles.value}>
                {data.employee.addressLine1}
                {data.employee.city ? `, ${data.employee.city}` : ''}
                {data.employee.region ? `, ${data.employee.region}` : ''}{' '}
                {data.employee.postalCode}
              </Text>
            </View>
          )}
        </View>

        <View style={styles.section}>
          <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>Employer</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Name:</Text>
            <Text style={styles.value}>{data.employer.name}</Text>
          </View>
          {data.employer.ein && (
            <View style={styles.row}>
              <Text style={styles.label}>EIN:</Text>
              <Text style={styles.value}>{data.employer.ein}</Text>
            </View>
          )}
        </View>

        <View style={styles.boxesGrid}>
          <View style={styles.box}>
            <Text style={styles.boxLabel}>Box 1 — Wages, tips, other compensation</Text>
            <Text style={styles.boxValue}>{fmt(data.box1WagesCents)}</Text>
          </View>
          <View style={styles.box}>
            <Text style={styles.boxLabel}>Box 2 — Federal income tax withheld</Text>
            <Text style={styles.boxValue}>{fmt(data.box2FederalTaxCents)}</Text>
          </View>
          <View style={styles.box}>
            <Text style={styles.boxLabel}>Box 3 — Social Security wages</Text>
            <Text style={styles.boxValue}>{fmt(data.box3SocialSecurityWagesCents)}</Text>
          </View>
          <View style={styles.box}>
            <Text style={styles.boxLabel}>Box 4 — Social Security tax withheld</Text>
            <Text style={styles.boxValue}>{fmt(data.box4SocialSecurityTaxCents)}</Text>
          </View>
          <View style={styles.box}>
            <Text style={styles.boxLabel}>Box 5 — Medicare wages</Text>
            <Text style={styles.boxValue}>{fmt(data.box5MedicareWagesCents)}</Text>
          </View>
          <View style={styles.box}>
            <Text style={styles.boxLabel}>Box 6 — Medicare tax withheld</Text>
            <Text style={styles.boxValue}>{fmt(data.box6MedicareTaxCents)}</Text>
          </View>
          {data.box15StateCode && (
            <>
              <View style={styles.box}>
                <Text style={styles.boxLabel}>Box 15 — State</Text>
                <Text style={styles.boxValue}>{data.box15StateCode}</Text>
              </View>
              <View style={styles.box}>
                <Text style={styles.boxLabel}>Box 16 — State wages</Text>
                <Text style={styles.boxValue}>{fmt(data.box16StateWagesCents)}</Text>
              </View>
              <View style={styles.box}>
                <Text style={styles.boxLabel}>Box 17 — State income tax</Text>
                <Text style={styles.boxValue}>{fmt(data.box17StateTaxCents)}</Text>
              </View>
            </>
          )}
          {data.box20LocalityName && (
            <>
              <View style={styles.box}>
                <Text style={styles.boxLabel}>Box 18 — Local wages</Text>
                <Text style={styles.boxValue}>{fmt(data.box18LocalWagesCents ?? 0)}</Text>
              </View>
              <View style={styles.box}>
                <Text style={styles.boxLabel}>Box 19 — Local income tax</Text>
                <Text style={styles.boxValue}>{fmt(data.box19LocalTaxCents ?? 0)}</Text>
              </View>
              <View style={styles.box}>
                <Text style={styles.boxLabel}>Box 20 — Locality name</Text>
                <Text style={styles.boxValue}>{data.box20LocalityName}</Text>
              </View>
            </>
          )}
        </View>

        <Text style={styles.footer}>
          This is a MyJova-generated W-2 statement. For official IRS-filing, use the
          structured e-file output. Tax year {data.taxYear}.
        </Text>
      </Page>
    </Document>
  )
}
