import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'

// =============================================================================
// WH-347 — Certified Payroll (Davis-Bacon) — versión legible simplificada.
// NO es el formulario oficial pixel-perfect; incluye los datos clave por
// trabajador y semana. Valida con tu agencia antes de certificar.
// =============================================================================

export type Wh347Worker = {
  name: string
  classification: string
  hoursByDay: number[] // 7 valores
  totalHours: number
  rateCents: number
  grossCents: number
}

export type Wh347Data = {
  contractor: string
  projectName: string
  contractNumber?: string
  weekStart: string
  weekEnd: string
  workers: Wh347Worker[]
}

const fmt = (c: number) => `$${(c / 100).toFixed(2)}`

const s = StyleSheet.create({
  page: { padding: 28, fontSize: 8, fontFamily: 'Helvetica', color: '#111' },
  h1: { fontSize: 13, fontWeight: 'bold' },
  sub: { fontSize: 8, color: '#555', marginBottom: 10 },
  meta: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  metaItem: { flexDirection: 'column' },
  label: { fontSize: 7, color: '#888' },
  value: { fontSize: 9, fontWeight: 'bold' },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#ddd', borderBottomStyle: 'solid', paddingVertical: 3 },
  head: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#111', borderBottomStyle: 'solid', paddingVertical: 3, fontWeight: 'bold' },
  cName: { width: '20%' },
  cClass: { width: '16%' },
  cDay: { width: '6.5%', textAlign: 'center' },
  cTot: { width: '7%', textAlign: 'right' },
  cRate: { width: '8%', textAlign: 'right' },
  cGross: { width: '10%', textAlign: 'right' },
  footer: { position: 'absolute', bottom: 20, left: 28, right: 28, fontSize: 7, color: '#999' },
})

export function Wh347Pdf({ data }: { data: Wh347Data }) {
  const days = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7']
  return (
    <Document>
      <Page size="LETTER" orientation="landscape" style={s.page}>
        <Text style={s.h1}>WH-347 — Certified Payroll</Text>
        <Text style={s.sub}>Statement of Compliance (Davis-Bacon) · Generated by MyJova</Text>

        <View style={s.meta}>
          <View style={s.metaItem}>
            <Text style={s.label}>Contractor</Text>
            <Text style={s.value}>{data.contractor}</Text>
          </View>
          <View style={s.metaItem}>
            <Text style={s.label}>Project</Text>
            <Text style={s.value}>{data.projectName}</Text>
          </View>
          <View style={s.metaItem}>
            <Text style={s.label}>Contract #</Text>
            <Text style={s.value}>{data.contractNumber || '—'}</Text>
          </View>
          <View style={s.metaItem}>
            <Text style={s.label}>Week</Text>
            <Text style={s.value}>{data.weekStart} → {data.weekEnd}</Text>
          </View>
        </View>

        <View style={s.head}>
          <Text style={s.cName}>Name</Text>
          <Text style={s.cClass}>Classification</Text>
          {days.map((d) => <Text key={d} style={s.cDay}>{d}</Text>)}
          <Text style={s.cTot}>Total</Text>
          <Text style={s.cRate}>Rate</Text>
          <Text style={s.cGross}>Gross</Text>
        </View>

        {data.workers.map((w, i) => (
          <View style={s.row} key={i}>
            <Text style={s.cName}>{w.name}</Text>
            <Text style={s.cClass}>{w.classification}</Text>
            {w.hoursByDay.map((h, j) => <Text key={j} style={s.cDay}>{h ? h.toFixed(1) : '—'}</Text>)}
            <Text style={s.cTot}>{w.totalHours.toFixed(1)}</Text>
            <Text style={s.cRate}>{fmt(w.rateCents)}</Text>
            <Text style={s.cGross}>{fmt(w.grossCents)}</Text>
          </View>
        ))}

        <Text style={s.footer}>
          MyJova-generated WH-347. Hours from approved time entries; gross = hours × hourly rate.
          Deductions/net are finalized in the payroll run. Validate before certifying.
        </Text>
      </Page>
    </Document>
  )
}
